[workspace]
members = [
    "day1-sonar-sweep",
    "day2-dive",
    "day3-binary-diagnostic",
    "day4-giant-squid",
    "day7-the-treachery-of-whales",
    "day8-seven-segment-search",
    "day9-smoke-basin",
]
